apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
      app: mongo
  ports:
        - protocol: TCP
          port: 27017
          targetPort: 27017

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
   database_url: mongodb-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: image1
  template:
    metadata:
      labels:
        app: image1
    spec:
      containers:
      - name: image1
        image: venuspathak/tech-eval:tag1
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_MONGO
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url

